apiVersion: apps/v1
kind: Deployment
metadata:
  name: delphi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delphi-backend
  template:
    metadata:
      labels:
        app: delphi-backend
    spec:
      containers:
        - name: api
          image: delphi-backend:latest
          ports:
            - containerPort: 8000
